[package]
name = "torrent"
version = "0.1.0"
edition = "2021"

[dependencies]
bendy = "0.3.3"
serde_json = "1.0"
serde_yaml = "0.9.25"
serde-xml-rs = "0.6.0"
serde = { version = "1", features = ["derive"] }
